AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  checkPricebookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: check-pricebook-function
      Runtime: python3.13
      Handler: app.lambda_handler
      CodeUri: .
      Timeout: 900
      MemorySize: 256
      Role: arn:aws:iam::759080473149:role/Write-tables-to-s3-role
